# Generated by Django 6.0.5 on 2026-05-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('E', 'Electrico'), ('T', 'Tierra'), ('L', 'Lagartija'), ('F', 'Fuego'), ('P', 'Planta')], max_length=30),
        ),
    ]
