# Generated by Django 6.0.5 on 2026-06-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lucha'), ('P', 'Planta'), ('F', 'Fuego'), ('E', 'Electrico'), ('T', 'Tierra'), ('A', 'Agua')], max_length=50),
        ),
    ]
