# Generated by Django 6.0.5 on 2026-06-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('A', 'Agua'), ('E', 'Electrico'), ('P', 'Planta'), ('L', 'Lucha'), ('F', 'Fuego')], max_length=50),
        ),
    ]
