# Generated by Django 4.2 on 2026-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_trainer_picture_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('A', 'Agua'), ('P', 'Planta'), ('E', 'Electrico'), ('F', 'Fuego'), ('L', 'Lucha')], max_length=50),
        ),
    ]
