# Generated by Django 4.2 on 2026-06-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('A', 'Agua'), ('P', 'Planta'), ('T', 'Tierra'), ('E', 'Electrico'), ('L', 'Lucha')], max_length=50),
        ),
    ]
