# Generated by Django 4.2 on 2026-06-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('L', 'Lucha'), ('P', 'Planta'), ('E', 'Electrico'), ('T', 'Tierra'), ('F', 'Fuego')], max_length=50),
        ),
    ]
